### ISSUE TITLE
calling issue

### ISSUE THREAD

**Issue by IronHide4** [ScottHamper/hackmud#1]
Im unsure how to actually call this cript.  When Im hacking a dead account and get the first lock I tried to use this script different ways.
user.pro_t1p
user.pro_t1p {target:#s.anon_2rc668.access_iqjqeh}
user.pro_t1p{}

but nothing I did worked.  I got these errors instead:
:::TRUST COMMUNICATION::: TypeError: Cannot read property 't' of null
:::TRUST COMMUNICATION::: TypeError: Cannot read property 'call' of undefined

**Comment by b0wti3** [comment]
After looking at the code, I think the issue is that when run it with a valid loc, you need to make sure the key is what the script is looking for.

> :::TRUST COMMUNICATION::: TypeError: Cannot read property 't' of null

Here, it is speaking about a property called 't'. When you look in the script for any arguments / variables called t, you get this line:

`).find(v => !(c[l] = v, r = a.t.call(c))`

Notice the call function - in hackmud, that is what runs a breach on a lock. So, t is what the script assumes is the loc.

Thus, when you did this:

> user.pro_t1p {target:#s.anon_2rc668.access_iqjqeh}

The script was confused, cause it was actually looking for this:

> user.pro_t1p {**_t_**:#s.anon_2rc668.access_iqjqeh}

Hope that answers your question. =)

**Comment by ScottHamper** [comment]
Thanks, @b0wti3 ! That's exactly it.

We don't have room for `arget`! Too many characters, :P
